### ISSUE TITLE
fix(peerIdFromKeys): private key unmarshal index out of range

### ISSUE THREAD

**Issue by nicobao** [libp2p/js-libp2p-peer-id#56]
Is `peerIdFromKeys(publicKey, privateKey)` broken? :( 

I noticed, that the public key length is validated, but not the private key length, while the private key is also constrained in size, leading to `Out of range` exception in my case.

Code:
```typescript
   import bls from '@chainsafe/bls'
   import { peerIdFromKeys } from '@libp2p/peer-id'

    const privateKey = bls.SecretKey.fromHex(v.privateKey), // v.privateKey is the privateKey as string below
    const publicKey = bls.PublicKey.fromHex(v.publicKey) // v.publicKey is the publicKey as string below

    const peerId = await peerIdFromKeys(publicKey.toBytes(), privateKey.toBytes())
```

Data:
```json
{
    "privateKey": "0x62039de9b1d1b6be0876b9335efb4bea26a9ddf8c2de07f30355b02b2f6eb852",
    "publicKey": "0x82aabcc20bb3982569fa198f1e27fcd20d33a5543d54b4645df972a713bf4d61b8eacf72d787132cc2fce5bf3c9803be"
}
```

Error
```bash
     RangeError: index out of range: 27 + 8 > 32
      at indexOutOfRange (node_modules/protobufjs/src/reader.js:13:12)
      at Reader.skip (node_modules/protobufjs/src/reader.js:338:19)
      at Reader.skipType (node_modules/protobufjs/src/reader.js:361:18)
      at Object.decode (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/@libp2p/crypto/src/keys/keys.ts:136:22)
      at decodeMessage (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/protons-runtime/src/decode.ts:8:16)
      at Object.PrivateKey.decode (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/@libp2p/crypto/src/keys/keys.ts:153:12)
      at unmarshalPrivateKey (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/@libp2p/crypto/src/keys/index.ts:86:38)
      at KeyChain.importPeer (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/libp2p/src/keychain/index.ts:523:32)
      at KeyChain.start (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/libp2p/src/keychain/index.ts:168:18)
      at async Promise.all (index 3)
      at Libp2pNode.start (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/libp2p/src/libp2p.ts:284:7)
      at createLibp2p (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/libp2p/src/index.ts:204:5)
      at ValidatorChatNode.createNode (file:///home/nicolas/nicobao/lodestar-test-solution/src/bundle.ts:101:18)
      at Context.<anonymous> (file:///home/nicolas/nicobao/lodestar-test-solution/test/bundle.spec.ts:18:7)
```

**Comment by nicobao** [comment]
Okay my bad, the `bls` lib I am using isn't using the same representation in Uin8Array than this library.
This library relies on a protobuf representation.

**Comment by nicobao** [comment]
In case someone google the error, I also got that:

```
1) libp2p bundle
       "before all" hook for "should connect one libp2p node to another":
     Error: invalid wire type 7 at offset 10
      at Reader.skipType (node_modules/protobufjs/src/reader.js:377:19)
      at Object.decode (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/@libp2p/crypto/src/keys/keys.ts:136:22)
      at decodeMessage (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/protons-runtime/src/decode.ts:8:16)
      at Object.PrivateKey.decode (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/@libp2p/crypto/src/keys/keys.ts:153:12)
      at unmarshalPrivateKey (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/@libp2p/crypto/src/keys/index.ts:86:38)
      at KeyChain.importPeer (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/libp2p/src/keychain/index.ts:523:32)
      at KeyChain.start (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/libp2p/src/keychain/index.ts:168:18)
      at async Promise.all (index 3)
      at Libp2pNode.start (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/libp2p/src/libp2p.ts:284:7)
      at createLibp2p (file:///home/nicolas/nicobao/lodestar-test-solution/node_modules/libp2p/src/index.ts:204:5)
      at ValidatorChatNode.createNode (file:///home/nicolas/nicobao/lodestar-test-solution/src/bundle.ts:101:18)
      at Context.<anonymous> (file:///home/nicolas/nicobao/lodestar-test-solution/test/bundle.spec.ts:18:7)
```
